spring:
  datasource:
    url: jdbc:mysql://192.168.1.101:4306/study_security?characterEncoding=UTF-8 #jdbc:mysql://192.168.40.13:30354/fanpin?characterEncoding=UTF-8
    username: root
    password: 123456
  security:
    user:
      name: lisi
      password: 123456
  thymeleaf:
    cache: true
    checkTemplate: true
    checkTemplateLocation: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    excludedViewNames:
  servlet:
    contentType: text/html
server:
  port: 8080

